/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Codorniz;
import Clases.Descuento;
import Clases.Huevos;
import java.util.Calendar;
import java.util.Date;
import java.util.Enumeration;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author esau_br
 */
public class Principal extends javax.swing.JFrame {
    
    static Codorniz[] codornices = new Codorniz[3];
    public int polluelos, adultos, jovenes, cantH,cantSacosP,cantSacosJ,cantSacosA;
    public double costoP,costoA , costoJ ,totalS, totalC , desc;
     Vector registro = new Vector();
       
        Calendar tiempo = Calendar.getInstance();
        String hora = String.valueOf(tiempo.get(Calendar.HOUR));
        String minutos = String.valueOf(tiempo.get(Calendar.MINUTE));
        String segundos = String.valueOf(tiempo.get(Calendar.SECOND));
        String dia = tiempo.getTime().toString();
        int amPM = tiempo.get(Calendar.AM_PM);     
        String reloj = hora + ':' + minutos +':'+segundos +'.'+ Jornada();
        
        
        
       String Jornada() {
            String resultado = null;
            
            switch (amPM){                
                case 0:
                    resultado = "AM";
                    break;                    
                case 1:                    
                    resultado = "PM";
                    break; 
                    
                default:
                    break;
            }           
            return resultado;            
        }
    
    public Principal() {
        initComponents();
        
        txtPrecioAdulto.setText("43200");
        txtPrecioJoven.setText("30045");
        txtPrecioPolluelo.setText("15840");
        txtPrecioHuevo.setText("6500");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tb_VentaHuevos = new javax.swing.JTabbedPane();
        Contenedor1 = new javax.swing.JPanel();
        ContenedorInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cantPolluelos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cantJovenes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cantAdultos = new javax.swing.JTextField();
        txt_cantHuevos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPrecioPolluelo = new javax.swing.JTextField();
        txtPrecioJoven = new javax.swing.JTextField();
        txtPrecioAdulto = new javax.swing.JTextField();
        checkModificaPrecio = new javax.swing.JCheckBox();
        ContenedorOutput = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtML_resultado = new javax.swing.JTextArea();
        btn_calcular = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnRegistraVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        registroVentasHuevos = new javax.swing.JTextArea();
        lblNombreCliente = new javax.swing.JLabel();
        lblCantHuevos = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtKilogramos = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chkModificaPrecioH = new javax.swing.JCheckBox();
        lblPRecioHuevo = new javax.swing.JLabel();
        txtPrecioHuevo = new javax.swing.JTextField();
        btnCalculaVenta = new javax.swing.JButton();
        btnImprimeRegistro = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabel1.setText("CodorSoft 2.0");

        Contenedor1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ContenedorInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setText("Precio de Alimentos");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel3.setText("Polluelos: ");

        txt_cantPolluelos.setName("txt_Polluelos"); // NOI18N

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel4.setText("Jovenes: ");

        txt_cantJovenes.setName("txt_Polluelos"); // NOI18N

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel5.setText("Adultos: ");

        txt_cantAdultos.setName("txt_Polluelos"); // NOI18N

        txt_cantHuevos.setName("txt_Polluelos"); // NOI18N

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jLabel6.setText("Huevos: ");

        jLabel10.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad de Codornices");

        txtPrecioPolluelo.setEditable(false);
        txtPrecioPolluelo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        txtPrecioPolluelo.setToolTipText("");

        txtPrecioJoven.setEditable(false);
        txtPrecioJoven.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N

        txtPrecioAdulto.setEditable(false);
        txtPrecioAdulto.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        txtPrecioAdulto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioAdultoActionPerformed(evt);
            }
        });

        checkModificaPrecio.setText("Modificar Precio");
        checkModificaPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkModificaPrecioMouseClicked(evt);
            }
        });
        checkModificaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkModificaPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorInputLayout = new javax.swing.GroupLayout(ContenedorInput);
        ContenedorInput.setLayout(ContenedorInputLayout);
        ContenedorInputLayout.setHorizontalGroup(
            ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_cantAdultos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantJovenes, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantPolluelos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrecioPolluelo)
                    .addComponent(txtPrecioJoven)
                    .addComponent(txtPrecioAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenedorInputLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkModificaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ContenedorInputLayout.setVerticalGroup(
            ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkModificaPrecio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ContenedorInputLayout.createSequentialGroup()
                        .addComponent(txtPrecioPolluelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioJoven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ContenedorInputLayout.createSequentialGroup()
                            .addComponent(txt_cantPolluelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_cantJovenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(18, 18, 18)
                            .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_cantAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addComponent(jLabel3)))
                .addGap(46, 46, 46)
                .addGroup(ContenedorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_cantHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
        );

        ContenedorOutput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel7.setText("Resultado e Informacion");

        txtML_resultado.setBackground(new java.awt.Color(159, 184, 236));
        txtML_resultado.setColumns(20);
        txtML_resultado.setRows(5);
        txtML_resultado.setName("resultados"); // NOI18N
        jScrollPane2.setViewportView(txtML_resultado);

        javax.swing.GroupLayout ContenedorOutputLayout = new javax.swing.GroupLayout(ContenedorOutput);
        ContenedorOutput.setLayout(ContenedorOutputLayout);
        ContenedorOutputLayout.setHorizontalGroup(
            ContenedorOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorOutputLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(ContenedorOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        ContenedorOutputLayout.setVerticalGroup(
            ContenedorOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorOutputLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        btn_calcular.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        btn_calcular.setText("CALCULAR");
        btn_calcular.setToolTipText("");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Contenedor1Layout = new javax.swing.GroupLayout(Contenedor1);
        Contenedor1.setLayout(Contenedor1Layout);
        Contenedor1Layout.setHorizontalGroup(
            Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenedor1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Contenedor1Layout.createSequentialGroup()
                        .addComponent(ContenedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(ContenedorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        Contenedor1Layout.setVerticalGroup(
            Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contenedor1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(Contenedor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ContenedorOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Contenedor1Layout.createSequentialGroup()
                        .addComponent(ContenedorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(btn_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tb_VentaHuevos.addTab("Compra Alimentos", Contenedor1);

        btnRegistraVenta.setText("Registrar Venta");
        btnRegistraVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistraVentaActionPerformed(evt);
            }
        });

        registroVentasHuevos.setColumns(20);
        registroVentasHuevos.setRows(5);
        jScrollPane1.setViewportView(registroVentasHuevos);

        lblNombreCliente.setText("Nombre Cliente: ");

        lblCantHuevos.setText("Kilogramos:");

        txtKilogramos.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtKilogramosCaretUpdate(evt);
            }
        });
        txtKilogramos.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtKilogramosInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtKilogramos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilogramosActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL");

        txtTOTAL.setEditable(false);
        txtTOTAL.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        txtTOTAL.setEnabled(false);
        txtTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOTALActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chkModificaPrecioH.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        chkModificaPrecioH.setText("Modifica Precio");
        chkModificaPrecioH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkModificaPrecioHMouseClicked(evt);
            }
        });

        lblPRecioHuevo.setText("Precio KG");

        txtPrecioHuevo.setEditable(false);
        txtPrecioHuevo.setFont(new java.awt.Font("DejaVu Sans", 3, 12)); // NOI18N
        txtPrecioHuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioHuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblPRecioHuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(chkModificaPrecioH, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(76, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRecioHuevo)
                    .addComponent(txtPrecioHuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(chkModificaPrecioH)
                    .addContainerGap(121, Short.MAX_VALUE)))
        );

        btnCalculaVenta.setText("CALCULA VENTA");
        btnCalculaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaVentaActionPerformed(evt);
            }
        });

        btnImprimeRegistro.setText("Muestra Registos");
        btnImprimeRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimeRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreCliente)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente)
                            .addComponent(txtKilogramos)))
                    .addComponent(btnCalculaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnImprimeRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistraVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreCliente)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantHuevos)
                            .addComponent(txtKilogramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotal)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculaVenta)))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistraVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tb_VentaHuevos.addTab("Venta de Huevos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel1)
                .addContainerGap(270, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tb_VentaHuevos)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(513, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(49, Short.MAX_VALUE)
                    .addComponent(tb_VentaHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        /*Este Metodo Calcula todo segun los datos ingresados

        */
        Descuento descuento;
        double precioP,precioA,precioJ;
       // GeneraTipoCodornices(codornices);

        try
        {
            int op;

            polluelos   = Integer.parseInt(txt_cantPolluelos.getText());
            jovenes     = Integer.parseInt(txt_cantJovenes.getText());
            adultos     = Integer.parseInt(txt_cantAdultos.getText());
            cantH       = Integer.parseInt(txt_cantHuevos.getText());
            
            precioP= Double.parseDouble(txtPrecioPolluelo.getText());
            precioJ = Double.parseDouble(txtPrecioJoven.getText());
            precioA = Double.parseDouble(txtPrecioAdulto.getText());

            descuento = new Descuento();
            descuento.setCantH(cantH);
            descuento.setDescuento(0);
            desc = descuento.getDescuento();

            cantSacosP = CantidadSacos(polluelos);
            cantSacosJ = CantidadSacos(jovenes);
            cantSacosA = CantidadSacos(adultos);
            

            costoP = CalculaCosto(cantSacosP,precioP);
            costoJ = CalculaCosto(cantSacosJ,precioJ);
            costoA = CalculaCosto(cantSacosA,precioA);

            totalS = costoP + costoJ + costoA;
            totalC = totalS -(totalS * desc);

            txtML_resultado.setText(ImprimeMensaje());

            op =  JOptionPane.showConfirmDialog(null, "Desea Realizar Otro Calculo","AVISO",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.YES_NO_CANCEL_OPTION);

            if(op==0)
            {
                txt_cantAdultos.setText("");
                txt_cantJovenes.setText("");
                txt_cantPolluelos.setText("");
                txt_cantHuevos.setText("");
                txtML_resultado.setText("");

            } else if (op==1)
            {
                System.exit(0);
            }

        } catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e.toString(),"ERROR" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void checkModificaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkModificaPrecioActionPerformed
        // TODO add your handling code here:
//        if(checkModificaPrecio.isSelected())
//        {
//            txtPrecioAdulto.setEditable(true);
//            txtPrecioJoven.setEditable(true);
//            txtPrecioPolluelo.setEditable(true);                    
//        }
//        
        
    }//GEN-LAST:event_checkModificaPrecioActionPerformed

    private void txtPrecioAdultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioAdultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioAdultoActionPerformed

    private void checkModificaPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkModificaPrecioMouseClicked
           
             if(checkModificaPrecio.isSelected())
        {
            txtPrecioAdulto.setEditable(true);
            txtPrecioJoven.setEditable(true);
            txtPrecioPolluelo.setEditable(true); 
            txtPrecioAdulto.setText("");
            txtPrecioJoven.setText("");
            txtPrecioPolluelo.setText("");
        }  else {
            txtPrecioAdulto.setEditable(false);
            txtPrecioJoven.setEditable(false);
            txtPrecioPolluelo.setEditable(false);
            txtPrecioAdulto.setText("43200");
            txtPrecioJoven.setText("30045");
            txtPrecioPolluelo.setText("15840");
             }
    }//GEN-LAST:event_checkModificaPrecioMouseClicked

    private void txtKilogramosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilogramosActionPerformed
        // TODO add your handling code here:
  
       
    }//GEN-LAST:event_txtKilogramosActionPerformed

    private void txtTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOTALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTOTALActionPerformed

    private void txtPrecioHuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioHuevoActionPerformed
        // TODO add your handling code here:
        
     
        
        
    }//GEN-LAST:event_txtPrecioHuevoActionPerformed

    private void chkModificaPrecioHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkModificaPrecioHMouseClicked
        // TODO add your handling code here:
        if(chkModificaPrecioH.isSelected())
        {
            txtPrecioHuevo.setEditable(true);
            txtPrecioHuevo.setText("");
            
            
        } else{
          
            txtPrecioHuevo.setEditable(false);
            txtPrecioHuevo.setText("6500");
            
            
        }
        
    }//GEN-LAST:event_chkModificaPrecioHMouseClicked

    private void btnRegistraVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistraVentaActionPerformed
        // Este metodo gener un vector con los datos de la venta y los va a agregando en el campo de texto
    try{    
        
         double precioH =   Double.parseDouble(txtPrecioHuevo.getText());
         double kg      =   Double.parseDouble(txtKilogramos.getText());
         double tot     =   Double.parseDouble (txtTOTAL.getText());
         
         double tKilosVendidos;
         double tVentas;
         
         Huevos venta = new Huevos(txtNombreCliente.getText(), precioH, kg, tot, reloj);
         
         registro.add(venta);
         
         txtNombreCliente.setText("");
         txtKilogramos.setText("");
         txtTOTAL.setText("");
         
         
        }   catch(Exception e){
         JOptionPane.showMessageDialog(null,e.toString(),"ERROR" , JOptionPane.ERROR_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btnRegistraVentaActionPerformed

    private void txtKilogramosInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtKilogramosInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilogramosInputMethodTextChanged

    private void txtKilogramosCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtKilogramosCaretUpdate
      
    }//GEN-LAST:event_txtKilogramosCaretUpdate

    private void btnCalculaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaVentaActionPerformed
        
      try 
        {  //realiza el calculo de la venta y muestra el total, hace uso de la clase Calendar para obtener la hora de venta
         
         hora = String.valueOf(tiempo.get(Calendar.HOUR));
         minutos = String.valueOf(tiempo.get(Calendar.MINUTE));
         segundos = String.valueOf(tiempo.get(Calendar.SECOND));
         dia = tiempo.getTime().toString();
         amPM = tiempo.get(Calendar.AM_PM);     
         reloj = hora + ':' + minutos +':'+segundos +'.'+ Jornada();
        
        
        
        
        double precio = Double.parseDouble(txtPrecioHuevo.getText());
        double kg = Double.parseDouble(txtKilogramos.getText());
        
        
       
        
        double resultado = precio * kg;
        
        txtTOTAL.setText(String.valueOf(resultado));
        } catch(Exception e){
             JOptionPane.showMessageDialog(null,e.toString(),"ERROR" , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalculaVentaActionPerformed

    private void btnImprimeRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimeRegistroActionPerformed
      
        // este metodo recorre el vector y muestra los resultados en el campo de texto
        String hilera="";
        int ventasDiarias=1;
        double totalidad=0;
        Huevos h;
        
        Enumeration vEnum = registro.elements();
        
        while(vEnum.hasMoreElements())
        {
            hilera+= vEnum.nextElement().toString()+ "\n";
            
            ventasDiarias++;
        }
        
        for(int i= 0; i<registro.size(); i++)
        {
            h = (Huevos)registro.get(i);
            
            totalidad += h.getTotal();
            
        }

         
         registroVentasHuevos.setText(hilera + "\n\n"+ 
              "Cantidad del Dia: " + ventasDiarias + "\n\n"+
              "Total Vendido:  ₡" + totalidad);
         
    }//GEN-LAST:event_btnImprimeRegistroActionPerformed

      public String ImprimeMensaje()
      {
        //Metodo que Imprime Mensajes
        String mensaje= "";
        
        mensaje+= "Cantidad de Codornices Polluelos = " + polluelos + "\n" +
                "Cantidad de Sacos para Polluelos = " + cantSacosP + "\n" +
                "Costo  =  ₡" + costoP  + "\n*****************\n" ;
       
        mensaje+= "Cantidad de Codornices Jovenes = " + jovenes + "\n" +
                "Cantidad de Sacos para Jovenes = " + cantSacosJ + "\n" +
                "Costo  =  ₡" + costoJ + "\n*****************\n" ;
        
        mensaje+= "Cantidad de Codornices Adultos = " + adultos + "\n" +
                "Cantidad de Sacos para Adultos = " + cantSacosA + "\n" +
                "Costo  =  ₡" + costoA + "\n*****************\n" ; 
        
        mensaje += "Costo Total sin Descuento =  ₡" + totalS + "\n*****************\n" ;
        mensaje += "Costo Total con Descuento =  ₡" + totalC + "\n*****************\n" ;
        
                
        return mensaje;
      }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
        GeneraTipoCodornices(codornices);     
        
        
        
        
 
    }
    
 
    
     public static int CantidadSacos(int cantCodor)
               /*realiza el calculo de sacos, tomando en consideracion la cantidad de
               codornices */
       {
           double consumo =0.5; //consume saco c/u codornices
           
           double resultado;
           
           resultado = (cantCodor%2 ==0)? (cantCodor * consumo) : ((cantCodor*consumo)+consumo);
           
             
           return (int)resultado;
           
       }
     
     public static double CalculaCosto(int cantSacos,double precio)
       {
         //Metodo que Calcula el Costo de Los Sacos
          return cantSacos * precio;
                    

       }
       
        public static void GeneraTipoCodornices(Codorniz[] c)
        {
            c[0] = new Codorniz(1, "Polluelo", "Crecimiento", 15840);
            c[1] = new Codorniz(2, "Joven", "Desarrollo", 30045);
            c[2] = new Codorniz(3, "Adulto", "Mantenimiento", 43200);
            
        }
        
            
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor1;
    private javax.swing.JPanel ContenedorInput;
    private javax.swing.JPanel ContenedorOutput;
    private javax.swing.JButton btnCalculaVenta;
    private javax.swing.JToggleButton btnImprimeRegistro;
    private javax.swing.JButton btnRegistraVenta;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JCheckBox checkModificaPrecio;
    private javax.swing.JCheckBox chkModificaPrecioH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantHuevos;
    private javax.swing.JLabel lblNombreCliente;
    private javax.swing.JLabel lblPRecioHuevo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea registroVentasHuevos;
    private javax.swing.JTabbedPane tb_VentaHuevos;
    private javax.swing.JTextField txtKilogramos;
    private javax.swing.JTextArea txtML_resultado;
    private javax.swing.JTextField txtNombreCliente;
    public javax.swing.JTextField txtPrecioAdulto;
    public javax.swing.JTextField txtPrecioHuevo;
    public javax.swing.JTextField txtPrecioJoven;
    public javax.swing.JTextField txtPrecioPolluelo;
    private javax.swing.JTextField txtTOTAL;
    private javax.swing.JTextField txt_cantAdultos;
    private javax.swing.JTextField txt_cantHuevos;
    private javax.swing.JTextField txt_cantJovenes;
    private javax.swing.JTextField txt_cantPolluelos;
    // End of variables declaration//GEN-END:variables
}
